### ISSUE TITLE
fxa-auth-server installation fails

### ISSUE THREAD

**Issue by fanatic82** [mozilla/fxa-auth-server#854]
While I'm trying to install the fxa-auth-server I get this error message:

fxcloud@raspberrypi ~/fxa-auth-server $ npm install
 
> bigint@0.4.2 install /home/fxcloud/fxa-auth-server/node_modules/bigint
> node-gyp configure build

make: Entering directory '/home/fxcloud/fxa-auth-server/node_modules/bigint/build'
  CXX(target) Release/obj.target/bigint/bigint.o
  SOLINK_MODULE(target) Release/obj.target/bigint.node
  SOLINK_MODULE(target) Release/obj.target/bigint.node: Finished
  COPY Release/bigint.node
make: Leaving directory '/home/fxcloud/fxa-auth-server/node_modules/bigint/build'
 
> scrypt-hash@1.1.8 install /home/fxcloud/fxa-auth-server/node_modules/scrypt-hash
> node-gyp rebuild

make: Entering directory '/home/fxcloud/fxa-auth-server/node_modules/scrypt-hash/build'
  CC(target) Release/obj.target/scrypt/crypto_scrypt-sse.o
../crypto_scrypt-sse.c:33:23: fatal error: emmintrin.h: No such file or directory
compilation terminated.
scrypt.target.mk:92: recipe for target 'Release/obj.target/scrypt/crypto_scrypt-sse.o' failed
make: *** [Release/obj.target/scrypt/crypto_scrypt-sse.o] Error 1
make: Leaving directory '/home/fxcloud/fxa-auth-server/node_modules/scrypt-hash/build'
gyp ERR! build error 
ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.12.35+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/fxcloud/fxa-auth-server/node_modules/scrypt-hash
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
 
> dtrace-provider@0.3.0 install /home/fxcloud/fxa-auth-server/node_modules/bunyan/node_modules/dtrace-provider
> scripts/install.js

 
> dtrace-provider@0.2.8 install /home/fxcloud/fxa-auth-server/node_modules/fxa-auth-db-mem/node_modules/fxa-auth-db-server/node_modules/restify/node_modules/dtrace-provider
> node-gyp rebuild

make: Entering directory '/home/fxcloud/fxa-auth-server/node_modules/fxa-auth-db-mem/node_modules/fxa-auth-db-server/node_modules/restify/node_modules/dtrace-provider/build'
  TOUCH Release/obj.target/DTraceProviderStub.stamp
make: Leaving directory '/home/fxcloud/fxa-auth-server/node_modules/fxa-auth-db-mem/node_modules/fxa-auth-db-server/node_modules/restify/node_modules/dtrace-provider/build'
 
> browserid-crypto@0.7.0 postinstall /home/fxcloud/fxa-auth-server/node_modules/browserid-crypto
> node ./scripts/bundle.js

/
****Bundling VEP for Browser****

\
***Packaging External Dependencies****

 
> dtrace-provider@0.2.8 install /home/fxcloud/fxa-auth-server/node_modules/fxa-auth-mailer/node_modules/restify/node_modules/dtrace-provider
> node-gyp rebuild

make: Entering directory '/home/fxcloud/fxa-auth-server/node_modules/fxa-auth-mailer/node_modules/restify/node_modules/dtrace-provider/build'
  TOUCH Release/obj.target/DTraceProviderStub.stamp
make: Leaving directory '/home/fxcloud/fxa-auth-server/node_modules/fxa-auth-mailer/node_modules/restify/node_modules/dtrace-provider/build'
npm ERR! scrypt-hash@1.1.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt-hash@1.1.8 install script.
npm ERR! This is most likely a problem with the scrypt-hash package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls scrypt-hash
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.12.35+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/fxcloud/fxa-auth-server
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

Anyone an idea, how I can fix this? Thanks.

OS: Raspbian GNU/Linux 7 \n \l
node v0.10.35
npm v2.1.18

**Comment by vladikoff** [comment]
@fanatic82 You need to find a way to fix this error `../crypto_scrypt-sse.c:33:23: fatal error: emmintrin.h: No such file or directory compilation terminated.` This is something to do with the fact that you are trying to install this on ARM architecture

**Comment by fanatic82** [comment]
Ok, thank you. I'll try and reply if I find a solution.

**Comment by rfk** [comment]
Looks like this may be reported upstream already: https://github.com/dannycoates/scrypt-hash/pull/5

**Comment by patricktokeeffe** [comment]
I see these errors too while trying to install in a debian 7.7.0 i386 vm with node 0.10.35, npm 1.4.28. There is an additional error with bigint.

````
rpi@debianvm:~/fxa-auth-server$ npm install
 
> bigint@0.4.2 install /home/rpi/fxa-auth-server/node_modules/bigint
> node-gyp configure build

make: Entering directory `/home/rpi/fxa-auth-server/node_modules/bigint/build'
  CXX(target) Release/obj.target/bigint/bigint.o
../bigint.cc:9:17: fatal error: gmp.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/bigint/bigint.o] Error 1
make: Leaving directory `/home/rpi/fxa-auth-server/node_modules/bigint/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.2.0-4-486
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/rpi/fxa-auth-server/node_modules/bigint
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
 
> scrypt-hash@1.1.8 install /home/rpi/fxa-auth-server/node_modules/scrypt-hash
> node-gyp rebuild

make: Entering directory `/home/rpi/fxa-auth-server/node_modules/scrypt-hash/build'
  CC(target) Release/obj.target/scrypt/crypto_scrypt-sse.o
In file included from ../crypto_scrypt-sse.c:33:0:
/usr/lib/gcc/i486-linux-gnu/4.7/include/emmintrin.h:32:3: error: #error "SSE2 instruction set not enabled"
../crypto_scrypt-sse.c:45:23: error: unknown type name ‘__m128i’
../crypto_scrypt-sse.c:46:29: error: unknown type name ‘__m128i’
../crypto_scrypt-sse.c:46:40: error: unknown type name ‘__m128i’
../crypto_scrypt-sse.c:46:51: error: unknown type name ‘__m128i’
../crypto_scrypt-sse.c: In function ‘blkcpy’:
../crypto_scrypt-sse.c:84:2: error: unknown type name ‘__m128i’
../crypto_scrypt-sse.c:85:2: error: unknown type name ‘__m128i’
../crypto_scrypt-sse.c: In function ‘blkxor’:
../crypto_scrypt-sse.c:96:2: error: unknown type name ‘__m128i’
../crypto_scrypt-sse.c:97:2: error: unknown type name ‘__m128i’
../crypto_scrypt-sse.c:102:3: warning: implicit declaration of function ‘_mm_xor_si128’ [-Wimplicit-function-declaration]
../crypto_scrypt-sse.c: At top level:
../crypto_scrypt-sse.c:110:11: error: unknown type name ‘__m128i’
../crypto_scrypt-sse.c:174:17: error: unknown type name ‘__m128i’
../crypto_scrypt-sse.c:174:32: error: unknown type name ‘__m128i’
../crypto_scrypt-sse.c:174:48: error: unknown type name ‘__m128i’
../crypto_scrypt-sse.c: In function ‘smix’:
../crypto_scrypt-sse.c:224:2: error: unknown type name ‘__m128i’
../crypto_scrypt-sse.c:225:2: error: unknown type name ‘__m128i’
../crypto_scrypt-sse.c:226:2: error: unknown type name ‘__m128i’
../crypto_scrypt-sse.c:242:10: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
../crypto_scrypt-sse.c:245:3: warning: implicit declaration of function ‘blockmix_salsa8’ [-Wimplicit-function-declaration]
../crypto_scrypt-sse.c:248:10: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
../crypto_scrypt-sse.c:261:13: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
../crypto_scrypt-sse.c:268:13: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
make: *** [Release/obj.target/scrypt/crypto_scrypt-sse.o] Error 1
make: Leaving directory `/home/rpi/fxa-auth-server/node_modules/scrypt-hash/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.2.0-4-486
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/rpi/fxa-auth-server/node_modules/scrypt-hash
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
 
> dtrace-provider@0.3.0 install /home/rpi/fxa-auth-server/node_modules/bunyan/node_modules/dtrace-provider
> scripts/install.js

 
> dtrace-provider@0.2.8 install /home/rpi/fxa-auth-server/node_modules/fxa-auth-db-mem/node_modules/fxa-auth-db-server/node_modules/restify/node_modules/dtrace-provider
> node-gyp rebuild

make: Entering directory `/home/rpi/fxa-auth-server/node_modules/fxa-auth-db-mem/node_modules/fxa-auth-db-server/node_modules/restify/node_modules/dtrace-provider/build'
  TOUCH Release/obj.target/DTraceProviderStub.stamp
make: Leaving directory `/home/rpi/fxa-auth-server/node_modules/fxa-auth-db-mem/node_modules/fxa-auth-db-server/node_modules/restify/node_modules/dtrace-provider/build'
 
> browserid-crypto@0.7.0 postinstall /home/rpi/fxa-auth-server/node_modules/browserid-crypto
> node ./scripts/bundle.js

|
****Bundling VEP for Browser****

\
***Packaging External Dependencies****

 
> dtrace-provider@0.2.8 install /home/rpi/fxa-auth-server/node_modules/fxa-auth-mailer/node_modules/restify/node_modules/dtrace-provider
> node-gyp rebuild

make: Entering directory `/home/rpi/fxa-auth-server/node_modules/fxa-auth-mailer/node_modules/restify/node_modules/dtrace-provider/build'
  TOUCH Release/obj.target/DTraceProviderStub.stamp
make: Leaving directory `/home/rpi/fxa-auth-server/node_modules/fxa-auth-mailer/node_modules/restify/node_modules/dtrace-provider/build'
npm ERR! bigint@0.4.2 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bigint@0.4.2 install script.
npm ERR! This is most likely a problem with the bigint package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bigint
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.2.0-4-486
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/rpi/fxa-auth-server
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
rpi@debianvm:~/fxa-auth-server$ 
````

**Comment by rfk** [comment]
>  There is an additional error with bigint.

For this one, you need to install libgmp and its development headers.

**Comment by patricktokeeffe** [comment]
> libgmp and its development headers

This is with libgmp-dev, libgmp10, libgmp3-dev, and libgmpxx4ldbl; all v2:5.0.5+dfsg-2

**Comment by vladikoff** [comment]
@patricktokeeffe see if you can install this module https://www.npmjs.com/package/bigint using `npm install bigint`. On Ubuntu we use `sudo apt-get install libgmp3-dev`

**Comment by patricktokeeffe** [comment]
@vladikoff I confirmed libgmp3-dev is newest version. `npm install bigint` succeeded and the bigint error is gone. 

The scrypt-hash error remains: SSE2 instruction set not enabled. I can see sse2 in my cpu flags though. Is there a way to check the compiler is receiving the -msse2 flag?

````
rpi@debianvm:~/fxa-auth-server$ sudo cat /proc/cpuinfo | grep flags
[sudo] password for rpi: 
flags		: fpu vme de pse tsc msr mce cx8 apic mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 constant_tsc pni monitor ssse3
````

**Comment by rfk** [comment]
This should be fixed with latest update to dependencies, closing

**Comment by arashst** [comment]
...if I may say, I still have the same problem on FreeBSD 10.1!
I got the error while executing the command: npm -V install

error Exit status 1
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/s/usr-local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System FreeBSD 10.1-RELEASE
gyp ERR! command "node" "/s/usr-local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /s/usr-local/fxa-auth-server/node_modules/bigint
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! FreeBSD 10.1-RELEASE
npm ERR! argv "node" "/usr/local/bin/npm" "-V" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.1
npm ERR! code ELIFECYCLE
npm ERR! bigint@0.4.2 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bigint@0.4.2 install script 'node-gyp configure build'.
npm ERR! This is most likely a problem with the bigint package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bigint

**Comment by arashst** [comment]
Upps, there is a problem with node 0.12 and bigint in FreeBSD, just installed node 0.10 using:
https://forums.freebsd.org/threads/need-help-building-bigint-cc.50538/
and it worked like a charm!

**Comment by jrgm** [comment]
Hi. Yes, it's known that bigint doesn't compile with node 0.12 -- https://github.com/mozilla/fxa-auth-server/issues/880. Good to hear that it builds for you with node 0.10 and FreeBSD.

**Comment by ROUGEXIII** [comment]
Hi,

I'm trying to install firefox sync + firefox account on raspberry too
First i got the same error as patricktokeeffe but solved it by downgrading the nodejs version to 0.10.28 and installing libgmp3-dev.
But now i have this error:
Error: /home/pi/fxa-auth-server/node_modules/scrypt-hash/build/Release/scrypt.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/home/pi/fxa-auth-server/node_modules/scrypt-hash/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/pi/fxa-auth-server/node_modules/scrypt-hash/index.js:1:97)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

Any help?
Is it possible possible to find a turorial about complete installation on raspberry pi?
Or can someone gives his history bash part from this?

PS: Sorry for my english, i'm french
